### ISSUE TITLE
GML (Geographic Markup Language) Support?

### ISSUE THREAD

**Issue by FilmCoder** [mapbox/leaflet-omnivore#89]
OGC's WFS protocol uses GML to transport vector features.  Will there be support added for this?

**Comment by tmcw** [comment]
Thanks for the suggestion! This is the first request of GML support. There are Leaflet plugins for GML/WFS:

1. https://github.com/respec/leaflet.wfs-t
2. https://github.com/Flexberry/Leaflet-WFST
3. https://github.com/azgs/azgs-leaflet

I think we should point to those plugins instead of supporting GML. leaflet-omnivore is a file format support module, and will not expand to being a service support module in order to support WFS, and the GML format is very rare outside of its role in WFS, and quite a complex format.

**Comment by FilmCoder** [comment]
Thanks so much!  I'm trying to maintain a front-end webpage with a map client which is able to consume WMS/WMTS, and now we're trying to add support for WFS which uses GML.  Do you think Leaflet is a good tool for this, or do you think we would be better off switching to a more feature-complete tool like OpenLayers, which has WFS/GML support built in?

We already have our map code written for leaflet so we're considering if we should switch.

Thanks so much for any advice you can offer!

ps.  I have been looking at the links you posted.  Some of them seem to be dead repos.  I also see that none of them explicitly support the GML Simple Features Profile.

**Comment by tmcw** [comment]
For GML, you might want to use OpenLayers: Leaflet is arguably better, more popular, and easier to use, but OpenLayers is more geared toward older and more corporate technology like WFS - it has the best WFS support out there.

**Comment by tmcw** [comment]
Closing; out of scope.
